-- Journal begins at Mon 2022-06-06 15:33:56 UTC, ends at Mon 2022-06-06 15:34:46 UTC. --
Jun 06 15:33:56 kind-worker2 systemd[1]: Condition check resulted in kubelet: The Kubernetes Node Agent being skipped.
Jun 06 15:34:29 kind-worker2 systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Jun 06 15:34:29 kind-worker2 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 06 15:34:29 kind-worker2 kubelet[291]: Flag --container-runtime has been deprecated, will be removed in 1.27 as the only valid value is 'remote'
Jun 06 15:34:29 kind-worker2 kubelet[291]: Flag --pod-infra-container-image has been deprecated, will be removed in 1.27. Image garbage collector will get sandbox image information from CRI.
Jun 06 15:34:29 kind-worker2 kubelet[291]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 06 15:34:29 kind-worker2 kubelet[291]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 06 15:34:29 kind-worker2 kubelet[291]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 06 15:34:29 kind-worker2 kubelet[291]: I0606 15:34:29.770957     291 server.go:193] "--pod-infra-container-image will not be pruned by the image garbage collector in kubelet and should also be set in the remote runtime"
Jun 06 15:34:29 kind-worker2 kubelet[291]: Flag --container-runtime has been deprecated, will be removed in 1.27 as the only valid value is 'remote'
Jun 06 15:34:29 kind-worker2 kubelet[291]: Flag --pod-infra-container-image has been deprecated, will be removed in 1.27. Image garbage collector will get sandbox image information from CRI.
Jun 06 15:34:29 kind-worker2 kubelet[291]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 06 15:34:29 kind-worker2 kubelet[291]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 06 15:34:29 kind-worker2 kubelet[291]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.643787     291 server.go:399] "Kubelet version" kubeletVersion="v1.24.0"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.643816     291 server.go:401] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.644098     291 server.go:813] "Client rotation is on, will bootstrap in background"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.646306     291 dynamic_cafile_content.go:157] "Starting controller" name="client-ca-bundle::/etc/kubernetes/pki/ca.crt"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.655335     291 container_manager_linux.go:262] "Container manager verified user specified cgroup-root exists" cgroupRoot=[kubelet]
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.655396     291 container_manager_linux.go:267] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: KubeletOOMScoreAdj:-999 ContainerRuntime: CgroupsPerQOS:true CgroupRoot:/kubelet CgroupDriver:systemd KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerPolicyOptions:map[] ExperimentalTopologyManagerScope:container ExperimentalCPUManagerReconcilePeriod:10s ExperimentalMemoryManagerPolicy:None ExperimentalMemoryManagerReservedMemory:[] ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.655418     291 topology_manager.go:133] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.655433     291 container_manager_linux.go:302] "Creating device plugin manager" devicePluginEnabled=true
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.655517     291 state_mem.go:36] "Initialized new in-memory state store"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.666798     291 kubelet.go:376] "Attempting to sync node with API server"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.666834     291 kubelet.go:267] "Adding static pod path" path="/etc/kubernetes/manifests"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.666855     291 kubelet.go:278] "Adding apiserver pod source"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.666868     291 apiserver.go:42] "Waiting for node sync before watching apiserver pods"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.667478     291 kuberuntime_manager.go:239] "Container runtime initialized" containerRuntime="containerd" version="v1.6.4" apiVersion="v1"
Jun 06 15:34:30 kind-worker2 kubelet[291]: W0606 15:34:30.667776     291 probe.go:268] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating.
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.668246     291 server.go:1181] "Started kubelet"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.668460     291 server.go:150] "Starting to listen" address="0.0.0.0" port=10250
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.674348     291 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.674919     291 volume_manager.go:289] "Starting Kubelet Volume Manager"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.675237     291 server.go:410] "Adding debug handlers to kubelet server"
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.675515     291 kubelet.go:2344] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.680280     291 desired_state_of_world_populator.go:145] "Desired state populator starts to run"
Jun 06 15:34:30 kind-worker2 kubelet[291]: W0606 15:34:30.680935     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.681068     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:30 kind-worker2 kubelet[291]: W0606 15:34:30.681880     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.681907     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:30 kind-worker2 kubelet[291]: W0606 15:34:30.681984     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.682011     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.682066     291 controller.go:144] failed to ensure lease exists, will retry in 200ms, error: leases.coordination.k8s.io "kind-worker2" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.684400     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82a85f1cc", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 668218828, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 668218828, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.720817     291 kubelet_network_linux.go:76] "Initialized protocol iptables rules." protocol=IPv4
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.732909     291 cpu_manager.go:213] "Starting CPU manager" policy="none"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.733048     291 cpu_manager.go:214] "Reconciling" reconcilePeriod="10s"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.733148     291 state_mem.go:36] "Initialized new in-memory state store"
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.733290     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53c80f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732040207, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732040207, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.734028     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53e036", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732046390, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732046390, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.734847     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53eeba", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732050106, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732050106, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.735773     291 policy_none.go:49] "None policy: Start"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.736316     291 memory_manager.go:168] "Starting memorymanager" policy="None"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.736418     291 state_mem.go:35] "Initializing new in-memory state store"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.754756     291 kubelet_network_linux.go:76] "Initialized protocol iptables rules." protocol=IPv6
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.754783     291 status_manager.go:161] "Starting to sync pod status with apiserver"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.754798     291 kubelet.go:1974] "Starting kubelet main sync loop"
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.754855     291 kubelet.go:1998] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
Jun 06 15:34:30 kind-worker2 kubelet[291]: W0606 15:34:30.756142     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.756172     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.780001     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.780940     291 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.782534     291 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker2"
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.782545     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53c80f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732040207, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 780896444, time.Local), Count:2, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53c80f" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.783391     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53e036", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732046390, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 780902469, time.Local), Count:2, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53e036" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.784170     291 manager.go:610] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.784202     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53eeba", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732050106, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 780906340, time.Local), Count:2, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53eeba" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.784396     291 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.784722     291 eviction_manager.go:254] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"kind-worker2\" not found"
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.786513     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f831888802", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeAllocatableEnforced", Message:"Updated Node Allocatable limit across pods", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 785828866, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 785828866, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.880256     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.883839     291 controller.go:144] failed to ensure lease exists, will retry in 400ms, error: leases.coordination.k8s.io "kind-worker2" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.981097     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:30 kind-worker2 kubelet[291]: I0606 15:34:30.984119     291 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.985590     291 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker2"
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.985664     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53c80f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732040207, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 984086734, time.Local), Count:3, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53c80f" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.986639     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53e036", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732046390, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 984093445, time.Local), Count:3, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53e036" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:30 kind-worker2 kubelet[291]: E0606 15:34:30.987644     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53eeba", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732050106, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 984096446, time.Local), Count:3, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53eeba" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.082072     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.182701     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.283310     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.285079     291 controller.go:144] failed to ensure lease exists, will retry in 800ms, error: leases.coordination.k8s.io "kind-worker2" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.383502     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:31 kind-worker2 kubelet[291]: I0606 15:34:31.386444     291 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.387751     291 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker2"
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.387763     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53c80f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732040207, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 386403586, time.Local), Count:4, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53c80f" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.388505     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53e036", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732046390, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 386419446, time.Local), Count:4, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53e036" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.470224     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53eeba", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732050106, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 386422730, time.Local), Count:4, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53eeba" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.484492     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.584897     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.685347     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:31 kind-worker2 kubelet[291]: W0606 15:34:31.733941     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.733973     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.785546     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:31 kind-worker2 kubelet[291]: W0606 15:34:31.810011     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.810047     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:31 kind-worker2 kubelet[291]: W0606 15:34:31.878585     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.878625     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.885857     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:31 kind-worker2 kubelet[291]: E0606 15:34:31.986468     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.086420     291 controller.go:144] failed to ensure lease exists, will retry in 1.6s, error: leases.coordination.k8s.io "kind-worker2" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.087447     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:32 kind-worker2 kubelet[291]: W0606 15:34:32.091450     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.091480     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.187969     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:32 kind-worker2 kubelet[291]: I0606 15:34:32.188698     291 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.190197     291 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker2"
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.190204     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53c80f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732040207, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 32, 188653169, time.Local), Count:5, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53c80f" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.191038     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53e036", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732046390, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 32, 188671901, time.Local), Count:5, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53e036" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.191877     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53eeba", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732050106, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 32, 188675419, time.Local), Count:5, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53eeba" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.288261     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.388833     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.489425     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.589920     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.690865     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.791897     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.892538     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:32 kind-worker2 kubelet[291]: E0606 15:34:32.993076     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.093610     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.194354     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.294983     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.395562     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.496112     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.596567     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.688250     291 controller.go:144] failed to ensure lease exists, will retry in 3.2s, error: leases.coordination.k8s.io "kind-worker2" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.697377     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:33 kind-worker2 kubelet[291]: I0606 15:34:33.791279     291 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.793109     291 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker2"
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.793101     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53c80f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732040207, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 33, 791198252, time.Local), Count:6, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53c80f" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.794465     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53e036", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732046390, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 33, 791214530, time.Local), Count:6, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53e036" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.795271     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53eeba", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732050106, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 33, 791243026, time.Local), Count:6, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53eeba" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.798350     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.898863     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:33 kind-worker2 kubelet[291]: W0606 15:34:33.980960     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.981006     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:33 kind-worker2 kubelet[291]: W0606 15:34:33.997895     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.997933     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:33 kind-worker2 kubelet[291]: E0606 15:34:33.998945     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:34 kind-worker2 kubelet[291]: W0606 15:34:34.072120     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:34 kind-worker2 kubelet[291]: E0606 15:34:34.072156     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:34 kind-worker2 kubelet[291]: E0606 15:34:34.099621     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:34 kind-worker2 kubelet[291]: E0606 15:34:34.200352     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:34 kind-worker2 kubelet[291]: E0606 15:34:34.300813     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:34 kind-worker2 kubelet[291]: E0606 15:34:34.401363     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:34 kind-worker2 kubelet[291]: E0606 15:34:34.501958     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:34 kind-worker2 kubelet[291]: E0606 15:34:34.602506     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:34 kind-worker2 kubelet[291]: E0606 15:34:34.702974     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:34 kind-worker2 kubelet[291]: E0606 15:34:34.804044     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:34 kind-worker2 kubelet[291]: E0606 15:34:34.904564     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:34 kind-worker2 kubelet[291]: W0606 15:34:34.935182     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Jun 06 15:34:34 kind-worker2 kubelet[291]: E0606 15:34:34.935240     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Jun 06 15:34:35 kind-worker2 kubelet[291]: E0606 15:34:35.005551     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:35 kind-worker2 kubelet[291]: E0606 15:34:35.105928     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:35 kind-worker2 kubelet[291]: E0606 15:34:35.206588     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:35 kind-worker2 kubelet[291]: E0606 15:34:35.307085     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:35 kind-worker2 kubelet[291]: E0606 15:34:35.407624     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:35 kind-worker2 kubelet[291]: E0606 15:34:35.508283     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:35 kind-worker2 kubelet[291]: E0606 15:34:35.608723     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:35 kind-worker2 kubelet[291]: E0606 15:34:35.709309     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:35 kind-worker2 kubelet[291]: E0606 15:34:35.785382     291 kubelet.go:2344] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Jun 06 15:34:35 kind-worker2 kubelet[291]: E0606 15:34:35.809807     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:35 kind-worker2 kubelet[291]: E0606 15:34:35.910324     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.010736     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.111385     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.212000     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.446204     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.547159     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.647755     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.748885     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.849814     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.891506     291 controller.go:144] failed to ensure lease exists, will retry in 6.4s, error: leases.coordination.k8s.io "kind-worker2" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.950734     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:36 kind-worker2 kubelet[291]: I0606 15:34:36.994927     291 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.996327     291 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker2"
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.996308     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53c80f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732040207, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 36, 994879720, time.Local), Count:7, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53c80f" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.997882     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53e036", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732046390, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 36, 994892622, time.Local), Count:7, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53e036" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:36 kind-worker2 kubelet[291]: E0606 15:34:36.998797     291 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.16f611f82e53eeba", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 732050106, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 36, 994897516, time.Local), Count:7, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.16f611f82e53eeba" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:37 kind-worker2 kubelet[291]: E0606 15:34:37.051109     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:37 kind-worker2 kubelet[291]: E0606 15:34:37.151911     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:37 kind-worker2 kubelet[291]: E0606 15:34:37.252739     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:37 kind-worker2 kubelet[291]: E0606 15:34:37.353296     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:37 kind-worker2 kubelet[291]: E0606 15:34:37.453931     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:37 kind-worker2 kubelet[291]: E0606 15:34:37.554580     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:37 kind-worker2 kubelet[291]: E0606 15:34:37.655226     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:37 kind-worker2 kubelet[291]: E0606 15:34:37.755357     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:37 kind-worker2 kubelet[291]: E0606 15:34:37.856269     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:37 kind-worker2 kubelet[291]: E0606 15:34:37.956726     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:38 kind-worker2 kubelet[291]: W0606 15:34:38.056386     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:38 kind-worker2 kubelet[291]: E0606 15:34:38.056428     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:38 kind-worker2 kubelet[291]: E0606 15:34:38.057458     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:38 kind-worker2 kubelet[291]: E0606 15:34:38.157820     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:38 kind-worker2 kubelet[291]: E0606 15:34:38.258497     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:38 kind-worker2 kubelet[291]: E0606 15:34:38.359189     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:38 kind-worker2 kubelet[291]: E0606 15:34:38.459808     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:38 kind-worker2 kubelet[291]: E0606 15:34:38.560361     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:38 kind-worker2 kubelet[291]: W0606 15:34:38.566559     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:38 kind-worker2 kubelet[291]: E0606 15:34:38.566602     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:38 kind-worker2 kubelet[291]: W0606 15:34:38.637173     291 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:38 kind-worker2 kubelet[291]: E0606 15:34:38.637211     291 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:38 kind-worker2 kubelet[291]: E0606 15:34:38.660558     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:38 kind-worker2 kubelet[291]: E0606 15:34:38.760766     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:38 kind-worker2 kubelet[291]: E0606 15:34:38.861529     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:38 kind-worker2 kubelet[291]: E0606 15:34:38.962045     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:39 kind-worker2 kubelet[291]: E0606 15:34:39.062660     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:39 kind-worker2 kubelet[291]: E0606 15:34:39.163381     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:39 kind-worker2 kubelet[291]: E0606 15:34:39.263898     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:39 kind-worker2 kubelet[291]: E0606 15:34:39.364575     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:39 kind-worker2 kubelet[291]: E0606 15:34:39.465826     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:39 kind-worker2 kubelet[291]: E0606 15:34:39.566471     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:39 kind-worker2 kubelet[291]: E0606 15:34:39.667048     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:39 kind-worker2 kubelet[291]: E0606 15:34:39.767391     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:39 kind-worker2 kubelet[291]: E0606 15:34:39.868052     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:39 kind-worker2 kubelet[291]: E0606 15:34:39.968608     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:40 kind-worker2 kubelet[291]: E0606 15:34:40.068685     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:40 kind-worker2 kubelet[291]: E0606 15:34:40.169046     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:40 kind-worker2 kubelet[291]: E0606 15:34:40.269598     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:40 kind-worker2 kubelet[291]: E0606 15:34:40.370032     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:40 kind-worker2 kubelet[291]: E0606 15:34:40.470567     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:40 kind-worker2 kubelet[291]: E0606 15:34:40.571026     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:40 kind-worker2 kubelet[291]: I0606 15:34:40.646572     291 transport.go:135] "Certificate rotation detected, shutting down client connections to start using new credentials"
Jun 06 15:34:40 kind-worker2 kubelet[291]: E0606 15:34:40.671794     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:40 kind-worker2 kubelet[291]: E0606 15:34:40.771966     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:40 kind-worker2 kubelet[291]: E0606 15:34:40.785526     291 eviction_manager.go:254] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"kind-worker2\" not found"
Jun 06 15:34:40 kind-worker2 kubelet[291]: E0606 15:34:40.785973     291 kubelet.go:2344] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Jun 06 15:34:40 kind-worker2 kubelet[291]: E0606 15:34:40.872572     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:40 kind-worker2 kubelet[291]: E0606 15:34:40.973016     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:41 kind-worker2 kubelet[291]: E0606 15:34:41.046386     291 csi_plugin.go:297] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: nodes "kind-worker2" not found
Jun 06 15:34:41 kind-worker2 kubelet[291]: E0606 15:34:41.073105     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:41 kind-worker2 kubelet[291]: E0606 15:34:41.174239     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:41 kind-worker2 kubelet[291]: E0606 15:34:41.274927     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:41 kind-worker2 kubelet[291]: E0606 15:34:41.375500     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:41 kind-worker2 kubelet[291]: E0606 15:34:41.476061     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:41 kind-worker2 kubelet[291]: E0606 15:34:41.576594     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:41 kind-worker2 kubelet[291]: E0606 15:34:41.677422     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:41 kind-worker2 kubelet[291]: E0606 15:34:41.778199     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:41 kind-worker2 kubelet[291]: E0606 15:34:41.878978     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:41 kind-worker2 kubelet[291]: E0606 15:34:41.979353     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:42 kind-worker2 kubelet[291]: E0606 15:34:42.079929     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:42 kind-worker2 kubelet[291]: E0606 15:34:42.180807     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:42 kind-worker2 kubelet[291]: E0606 15:34:42.281229     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:42 kind-worker2 kubelet[291]: E0606 15:34:42.284508     291 csi_plugin.go:297] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: nodes "kind-worker2" not found
Jun 06 15:34:42 kind-worker2 kubelet[291]: E0606 15:34:42.381977     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:42 kind-worker2 kubelet[291]: E0606 15:34:42.482729     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:42 kind-worker2 kubelet[291]: E0606 15:34:42.583730     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:42 kind-worker2 kubelet[291]: E0606 15:34:42.684711     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:42 kind-worker2 kubelet[291]: E0606 15:34:42.785098     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:42 kind-worker2 kubelet[291]: E0606 15:34:42.885184     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:42 kind-worker2 kubelet[291]: E0606 15:34:42.985752     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:43 kind-worker2 kubelet[291]: E0606 15:34:43.085849     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:43 kind-worker2 kubelet[291]: E0606 15:34:43.186007     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:43 kind-worker2 kubelet[291]: E0606 15:34:43.286114     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:43 kind-worker2 kubelet[291]: E0606 15:34:43.295485     291 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"kind-worker2\" not found" node="kind-worker2"
Jun 06 15:34:43 kind-worker2 kubelet[291]: E0606 15:34:43.386883     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:43 kind-worker2 kubelet[291]: I0606 15:34:43.397726     291 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Jun 06 15:34:43 kind-worker2 kubelet[291]: E0606 15:34:43.487922     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:43 kind-worker2 kubelet[291]: E0606 15:34:43.588513     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:43 kind-worker2 kubelet[291]: I0606 15:34:43.686153     291 kubelet_node_status.go:73] "Successfully registered node" node="kind-worker2"
Jun 06 15:34:43 kind-worker2 kubelet[291]: E0606 15:34:43.689080     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:43 kind-worker2 kubelet[291]: E0606 15:34:43.789816     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:43 kind-worker2 kubelet[291]: E0606 15:34:43.890882     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:43 kind-worker2 kubelet[291]: E0606 15:34:43.991590     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:44 kind-worker2 kubelet[291]: E0606 15:34:44.092364     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:44 kind-worker2 kubelet[291]: E0606 15:34:44.193232     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:44 kind-worker2 kubelet[291]: E0606 15:34:44.294001     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:44 kind-worker2 kubelet[291]: E0606 15:34:44.394283     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:44 kind-worker2 kubelet[291]: E0606 15:34:44.494873     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:44 kind-worker2 kubelet[291]: E0606 15:34:44.595627     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:44 kind-worker2 kubelet[291]: E0606 15:34:44.696678     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:44 kind-worker2 kubelet[291]: E0606 15:34:44.796761     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:44 kind-worker2 kubelet[291]: E0606 15:34:44.897487     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:44 kind-worker2 kubelet[291]: E0606 15:34:44.998128     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:45 kind-worker2 kubelet[291]: E0606 15:34:45.098904     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:45 kind-worker2 kubelet[291]: E0606 15:34:45.199722     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:45 kind-worker2 kubelet[291]: E0606 15:34:45.300354     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:45 kind-worker2 kubelet[291]: E0606 15:34:45.401189     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:45 kind-worker2 kubelet[291]: E0606 15:34:45.501802     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:45 kind-worker2 kubelet[291]: E0606 15:34:45.602515     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:45 kind-worker2 kubelet[291]: E0606 15:34:45.703536     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:45 kind-worker2 kubelet[291]: E0606 15:34:45.786981     291 kubelet.go:2344] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Jun 06 15:34:45 kind-worker2 kubelet[291]: E0606 15:34:45.804082     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:45 kind-worker2 kubelet[291]: E0606 15:34:45.905057     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
Jun 06 15:34:46 kind-worker2 kubelet[291]: E0606 15:34:46.007663     291 kubelet.go:2419] "Error getting node" err="node \"kind-worker2\" not found"
