-- Journal begins at Mon 2022-06-06 15:33:56 UTC, ends at Mon 2022-06-06 15:34:45 UTC. --
Jun 06 15:33:56 kind-worker3 systemd[1]: Condition check resulted in kubelet: The Kubernetes Node Agent being skipped.
Jun 06 15:34:29 kind-worker3 systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Jun 06 15:34:29 kind-worker3 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 06 15:34:29 kind-worker3 kubelet[294]: Flag --container-runtime has been deprecated, will be removed in 1.27 as the only valid value is 'remote'
Jun 06 15:34:29 kind-worker3 kubelet[294]: Flag --pod-infra-container-image has been deprecated, will be removed in 1.27. Image garbage collector will get sandbox image information from CRI.
Jun 06 15:34:29 kind-worker3 kubelet[294]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 06 15:34:29 kind-worker3 kubelet[294]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 06 15:34:29 kind-worker3 kubelet[294]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 06 15:34:29 kind-worker3 kubelet[294]: I0606 15:34:29.774849     294 server.go:193] "--pod-infra-container-image will not be pruned by the image garbage collector in kubelet and should also be set in the remote runtime"
Jun 06 15:34:29 kind-worker3 kubelet[294]: Flag --container-runtime has been deprecated, will be removed in 1.27 as the only valid value is 'remote'
Jun 06 15:34:29 kind-worker3 kubelet[294]: Flag --pod-infra-container-image has been deprecated, will be removed in 1.27. Image garbage collector will get sandbox image information from CRI.
Jun 06 15:34:29 kind-worker3 kubelet[294]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 06 15:34:29 kind-worker3 kubelet[294]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 06 15:34:29 kind-worker3 kubelet[294]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.952045     294 server.go:399] "Kubelet version" kubeletVersion="v1.24.0"
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.952073     294 server.go:401] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.952342     294 server.go:813] "Client rotation is on, will bootstrap in background"
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.954207     294 dynamic_cafile_content.go:157] "Starting controller" name="client-ca-bundle::/etc/kubernetes/pki/ca.crt"
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.964071     294 container_manager_linux.go:262] "Container manager verified user specified cgroup-root exists" cgroupRoot=[kubelet]
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.964142     294 container_manager_linux.go:267] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: KubeletOOMScoreAdj:-999 ContainerRuntime: CgroupsPerQOS:true CgroupRoot:/kubelet CgroupDriver:systemd KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerPolicyOptions:map[] ExperimentalTopologyManagerScope:container ExperimentalCPUManagerReconcilePeriod:10s ExperimentalMemoryManagerPolicy:None ExperimentalMemoryManagerReservedMemory:[] ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.964167     294 topology_manager.go:133] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.964180     294 container_manager_linux.go:302] "Creating device plugin manager" devicePluginEnabled=true
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.964266     294 state_mem.go:36] "Initialized new in-memory state store"
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.969653     294 kubelet.go:376] "Attempting to sync node with API server"
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.969680     294 kubelet.go:267] "Adding static pod path" path="/etc/kubernetes/manifests"
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.969714     294 kubelet.go:278] "Adding apiserver pod source"
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.969731     294 apiserver.go:42] "Waiting for node sync before watching apiserver pods"
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.970331     294 kuberuntime_manager.go:239] "Container runtime initialized" containerRuntime="containerd" version="v1.6.4" apiVersion="v1"
Jun 06 15:34:30 kind-worker3 kubelet[294]: W0606 15:34:30.970672     294 probe.go:268] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating.
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.971220     294 server.go:1181] "Started kubelet"
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.972111     294 server.go:150] "Starting to listen" address="0.0.0.0" port=10250
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.974418     294 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.974449     294 server.go:410] "Adding debug handlers to kubelet server"
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.975268     294 volume_manager.go:289] "Starting Kubelet Volume Manager"
Jun 06 15:34:30 kind-worker3 kubelet[294]: I0606 15:34:30.975347     294 desired_state_of_world_populator.go:145] "Desired state populator starts to run"
Jun 06 15:34:30 kind-worker3 kubelet[294]: E0606 15:34:30.977612     294 kubelet.go:2344] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Jun 06 15:34:30 kind-worker3 kubelet[294]: W0606 15:34:30.984607     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:30 kind-worker3 kubelet[294]: E0606 15:34:30.984654     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:30 kind-worker3 kubelet[294]: E0606 15:34:30.984584     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f83c951c7d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 971202685, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 30, 971202685, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:30 kind-worker3 kubelet[294]: E0606 15:34:30.985723     294 controller.go:144] failed to ensure lease exists, will retry in 200ms, error: leases.coordination.k8s.io "kind-worker3" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Jun 06 15:34:30 kind-worker3 kubelet[294]: W0606 15:34:30.985868     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: nodes "kind-worker3" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:30 kind-worker3 kubelet[294]: E0606 15:34:30.985964     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes "kind-worker3" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:30 kind-worker3 kubelet[294]: W0606 15:34:30.985966     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:30 kind-worker3 kubelet[294]: E0606 15:34:30.985996     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.024673     294 kubelet_network_linux.go:76] "Initialized protocol iptables rules." protocol=IPv4
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.041508     294 cpu_manager.go:213] "Starting CPU manager" policy="none"
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.041532     294 cpu_manager.go:214] "Reconciling" reconcilePeriod="10s"
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.041549     294 state_mem.go:36] "Initialized new in-memory state store"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.042020     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd1861", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker3 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40931937, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40931937, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.043835     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd4fe3", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker3 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40946147, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40946147, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.044248     294 policy_none.go:49] "None policy: Start"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.044603     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd5c9a", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker3 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40949402, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40949402, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.045005     294 memory_manager.go:168] "Starting memorymanager" policy="None"
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.045052     294 state_mem.go:35] "Initializing new in-memory state store"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.076402     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.077417     294 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker3"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.078642     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd1861", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker3 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40931937, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 77367166, time.Local), Count:2, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd1861" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.078722     294 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker3"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.079418     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd4fe3", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker3 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40946147, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 77381647, time.Local), Count:2, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd4fe3" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.080152     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd5c9a", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker3 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40949402, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 77386093, time.Local), Count:2, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd5c9a" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.101297     294 kubelet_network_linux.go:76] "Initialized protocol iptables rules." protocol=IPv6
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.101325     294 status_manager.go:161] "Starting to sync pod status with apiserver"
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.101346     294 kubelet.go:1974] "Starting kubelet main sync loop"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.101392     294 kubelet.go:1998] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
Jun 06 15:34:31 kind-worker3 kubelet[294]: W0606 15:34:31.102756     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.102804     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.108556     294 manager.go:610] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.108813     294 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.109796     294 eviction_manager.go:254] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"kind-worker3\" not found"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.111961     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f844dbe81e", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeAllocatableEnforced", Message:"Updated Node Allocatable limit across pods", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 110060062, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 110060062, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.176907     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.187802     294 controller.go:144] failed to ensure lease exists, will retry in 400ms, error: leases.coordination.k8s.io "kind-worker3" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.277231     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.280112     294 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker3"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.281435     294 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker3"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.281437     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd1861", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker3 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40931937, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 280073435, time.Local), Count:3, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd1861" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.282245     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd4fe3", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker3 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40946147, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 280086395, time.Local), Count:3, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd4fe3" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.282998     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd5c9a", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker3 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40949402, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 280089774, time.Local), Count:3, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd5c9a" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.377424     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.478085     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.578495     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.589787     294 controller.go:144] failed to ensure lease exists, will retry in 800ms, error: leases.coordination.k8s.io "kind-worker3" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.679172     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:31 kind-worker3 kubelet[294]: I0606 15:34:31.683125     294 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker3"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.684272     294 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker3"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.684282     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd1861", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker3 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40931937, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 683084997, time.Local), Count:4, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd1861" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.685210     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd4fe3", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker3 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40946147, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 683098843, time.Local), Count:4, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd4fe3" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.772543     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd5c9a", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker3 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40949402, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 683101891, time.Local), Count:4, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd5c9a" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.779819     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:31 kind-worker3 kubelet[294]: W0606 15:34:31.832130     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.832170     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.880450     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:31 kind-worker3 kubelet[294]: E0606 15:34:31.981284     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:32 kind-worker3 kubelet[294]: W0606 15:34:32.035193     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.035227     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.081431     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:32 kind-worker3 kubelet[294]: W0606 15:34:32.131019     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: nodes "kind-worker3" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.131059     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes "kind-worker3" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.182304     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.282692     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.383159     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.391285     294 controller.go:144] failed to ensure lease exists, will retry in 1.6s, error: leases.coordination.k8s.io "kind-worker3" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.483831     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:32 kind-worker3 kubelet[294]: I0606 15:34:32.485651     294 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker3"
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.487020     294 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker3"
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.487008     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd1861", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker3 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40931937, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 32, 485611090, time.Local), Count:5, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd1861" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.487891     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd4fe3", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker3 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40946147, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 32, 485622098, time.Local), Count:5, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd4fe3" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.488674     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd5c9a", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker3 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40949402, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 32, 485625991, time.Local), Count:5, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd5c9a" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.584082     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:32 kind-worker3 kubelet[294]: W0606 15:34:32.664078     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.664115     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.684391     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.784856     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.885372     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:32 kind-worker3 kubelet[294]: E0606 15:34:32.986286     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:33 kind-worker3 kubelet[294]: E0606 15:34:33.086454     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:33 kind-worker3 kubelet[294]: E0606 15:34:33.187156     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:33 kind-worker3 kubelet[294]: E0606 15:34:33.287617     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:33 kind-worker3 kubelet[294]: E0606 15:34:33.388032     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:33 kind-worker3 kubelet[294]: E0606 15:34:33.488723     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:33 kind-worker3 kubelet[294]: E0606 15:34:33.589149     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:33 kind-worker3 kubelet[294]: E0606 15:34:33.689568     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:33 kind-worker3 kubelet[294]: E0606 15:34:33.789969     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:33 kind-worker3 kubelet[294]: E0606 15:34:33.890409     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:33 kind-worker3 kubelet[294]: E0606 15:34:33.991044     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:33 kind-worker3 kubelet[294]: E0606 15:34:33.993424     294 controller.go:144] failed to ensure lease exists, will retry in 3.2s, error: leases.coordination.k8s.io "kind-worker3" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Jun 06 15:34:34 kind-worker3 kubelet[294]: I0606 15:34:34.088610     294 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker3"
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.090023     294 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker3"
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.090024     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd1861", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker3 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40931937, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 34, 88565846, time.Local), Count:6, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd1861" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.090869     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd4fe3", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker3 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40946147, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 34, 88580577, time.Local), Count:6, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd4fe3" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.091107     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.091699     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd5c9a", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker3 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40949402, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 34, 88583836, time.Local), Count:6, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd5c9a" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:34 kind-worker3 kubelet[294]: W0606 15:34:34.103744     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.103773     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.192141     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.292578     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.393003     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.493646     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:34 kind-worker3 kubelet[294]: W0606 15:34:34.572909     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: nodes "kind-worker3" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.572944     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes "kind-worker3" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.594175     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.694614     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.795355     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.895858     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:34 kind-worker3 kubelet[294]: E0606 15:34:34.996897     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:35 kind-worker3 kubelet[294]: W0606 15:34:35.094683     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:35 kind-worker3 kubelet[294]: E0606 15:34:35.094724     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Jun 06 15:34:35 kind-worker3 kubelet[294]: E0606 15:34:35.097815     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:35 kind-worker3 kubelet[294]: E0606 15:34:35.198429     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:35 kind-worker3 kubelet[294]: E0606 15:34:35.298885     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:35 kind-worker3 kubelet[294]: E0606 15:34:35.399380     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:35 kind-worker3 kubelet[294]: E0606 15:34:35.499951     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:35 kind-worker3 kubelet[294]: E0606 15:34:35.600377     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:35 kind-worker3 kubelet[294]: E0606 15:34:35.700802     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:35 kind-worker3 kubelet[294]: W0606 15:34:35.712104     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Jun 06 15:34:35 kind-worker3 kubelet[294]: E0606 15:34:35.712136     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Jun 06 15:34:35 kind-worker3 kubelet[294]: E0606 15:34:35.801403     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:35 kind-worker3 kubelet[294]: E0606 15:34:35.901808     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:36 kind-worker3 kubelet[294]: E0606 15:34:36.002622     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:36 kind-worker3 kubelet[294]: E0606 15:34:36.103175     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:36 kind-worker3 kubelet[294]: E0606 15:34:36.109736     294 kubelet.go:2344] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Jun 06 15:34:36 kind-worker3 kubelet[294]: E0606 15:34:36.203399     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:36 kind-worker3 kubelet[294]: E0606 15:34:36.303869     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:36 kind-worker3 kubelet[294]: E0606 15:34:36.404113     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:36 kind-worker3 kubelet[294]: E0606 15:34:36.504574     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:36 kind-worker3 kubelet[294]: E0606 15:34:36.605274     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:36 kind-worker3 kubelet[294]: E0606 15:34:36.706135     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:36 kind-worker3 kubelet[294]: E0606 15:34:36.842341     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:36 kind-worker3 kubelet[294]: E0606 15:34:36.942946     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.043547     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.146013     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.243549     294 controller.go:144] failed to ensure lease exists, will retry in 6.4s, error: leases.coordination.k8s.io "kind-worker3" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.246800     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:37 kind-worker3 kubelet[294]: I0606 15:34:37.319405     294 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker3"
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.322101     294 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker3"
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.322321     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd1861", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker3 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40931937, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 37, 319311706, time.Local), Count:7, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd1861" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.323396     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd4fe3", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker3 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40946147, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 37, 319323270, time.Local), Count:7, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd4fe3" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.324184     294 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker3.16f611f840bd5c9a", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker3", UID:"kind-worker3", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker3 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker3"}, FirstTimestamp:time.Date(2022, time.June, 6, 15, 34, 31, 40949402, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 15, 34, 37, 319326525, time.Local), Count:7, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker3.16f611f840bd5c9a" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.347366     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.465860     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.566354     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.666932     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.767652     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.868079     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:37 kind-worker3 kubelet[294]: E0606 15:34:37.968786     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:38 kind-worker3 kubelet[294]: E0606 15:34:38.069124     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:38 kind-worker3 kubelet[294]: E0606 15:34:38.169954     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:38 kind-worker3 kubelet[294]: W0606 15:34:38.198631     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:38 kind-worker3 kubelet[294]: E0606 15:34:38.198666     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Jun 06 15:34:38 kind-worker3 kubelet[294]: E0606 15:34:38.270800     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:38 kind-worker3 kubelet[294]: E0606 15:34:38.371267     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:38 kind-worker3 kubelet[294]: E0606 15:34:38.471764     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:38 kind-worker3 kubelet[294]: E0606 15:34:38.572387     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:38 kind-worker3 kubelet[294]: E0606 15:34:38.672713     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:38 kind-worker3 kubelet[294]: E0606 15:34:38.773155     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:38 kind-worker3 kubelet[294]: E0606 15:34:38.873579     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:38 kind-worker3 kubelet[294]: E0606 15:34:38.974173     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:39 kind-worker3 kubelet[294]: E0606 15:34:39.074415     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:39 kind-worker3 kubelet[294]: E0606 15:34:39.175286     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:39 kind-worker3 kubelet[294]: E0606 15:34:39.275703     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:39 kind-worker3 kubelet[294]: W0606 15:34:39.319577     294 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: nodes "kind-worker3" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:39 kind-worker3 kubelet[294]: E0606 15:34:39.320985     294 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes "kind-worker3" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jun 06 15:34:39 kind-worker3 kubelet[294]: E0606 15:34:39.376368     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:39 kind-worker3 kubelet[294]: E0606 15:34:39.481016     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:39 kind-worker3 kubelet[294]: E0606 15:34:39.581215     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:39 kind-worker3 kubelet[294]: E0606 15:34:39.681681     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:39 kind-worker3 kubelet[294]: E0606 15:34:39.782156     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:39 kind-worker3 kubelet[294]: E0606 15:34:39.882730     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:39 kind-worker3 kubelet[294]: E0606 15:34:39.988276     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:40 kind-worker3 kubelet[294]: E0606 15:34:40.089019     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:40 kind-worker3 kubelet[294]: E0606 15:34:40.190533     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:40 kind-worker3 kubelet[294]: E0606 15:34:40.290938     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:40 kind-worker3 kubelet[294]: E0606 15:34:40.391383     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:40 kind-worker3 kubelet[294]: E0606 15:34:40.503397     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:40 kind-worker3 kubelet[294]: E0606 15:34:40.660694     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:40 kind-worker3 kubelet[294]: E0606 15:34:40.761140     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:40 kind-worker3 kubelet[294]: E0606 15:34:40.861543     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:40 kind-worker3 kubelet[294]: I0606 15:34:40.953870     294 transport.go:135] "Certificate rotation detected, shutting down client connections to start using new credentials"
Jun 06 15:34:40 kind-worker3 kubelet[294]: E0606 15:34:40.962176     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:41 kind-worker3 kubelet[294]: E0606 15:34:41.062422     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:41 kind-worker3 kubelet[294]: E0606 15:34:41.110581     294 eviction_manager.go:254] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"kind-worker3\" not found"
Jun 06 15:34:41 kind-worker3 kubelet[294]: E0606 15:34:41.111062     294 kubelet.go:2344] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Jun 06 15:34:41 kind-worker3 kubelet[294]: E0606 15:34:41.163226     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:41 kind-worker3 kubelet[294]: E0606 15:34:41.263783     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:41 kind-worker3 kubelet[294]: E0606 15:34:41.364323     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:41 kind-worker3 kubelet[294]: E0606 15:34:41.464853     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:41 kind-worker3 kubelet[294]: E0606 15:34:41.482568     294 csi_plugin.go:297] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: nodes "kind-worker3" not found
Jun 06 15:34:41 kind-worker3 kubelet[294]: E0606 15:34:41.565121     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:41 kind-worker3 kubelet[294]: E0606 15:34:41.666104     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:41 kind-worker3 kubelet[294]: E0606 15:34:41.766167     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:41 kind-worker3 kubelet[294]: E0606 15:34:41.866599     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:41 kind-worker3 kubelet[294]: E0606 15:34:41.967378     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:42 kind-worker3 kubelet[294]: E0606 15:34:42.068526     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:42 kind-worker3 kubelet[294]: E0606 15:34:42.169443     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:42 kind-worker3 kubelet[294]: E0606 15:34:42.270250     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:42 kind-worker3 kubelet[294]: E0606 15:34:42.370608     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:42 kind-worker3 kubelet[294]: E0606 15:34:42.471415     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:42 kind-worker3 kubelet[294]: E0606 15:34:42.571744     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:42 kind-worker3 kubelet[294]: E0606 15:34:42.672801     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:42 kind-worker3 kubelet[294]: E0606 15:34:42.773186     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:42 kind-worker3 kubelet[294]: E0606 15:34:42.787742     294 csi_plugin.go:297] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: nodes "kind-worker3" not found
Jun 06 15:34:42 kind-worker3 kubelet[294]: E0606 15:34:42.873936     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:42 kind-worker3 kubelet[294]: E0606 15:34:42.974682     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:43 kind-worker3 kubelet[294]: E0606 15:34:43.075707     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:43 kind-worker3 kubelet[294]: E0606 15:34:43.176297     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:43 kind-worker3 kubelet[294]: E0606 15:34:43.277208     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:43 kind-worker3 kubelet[294]: E0606 15:34:43.377529     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:43 kind-worker3 kubelet[294]: E0606 15:34:43.478549     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:43 kind-worker3 kubelet[294]: E0606 15:34:43.579007     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:43 kind-worker3 kubelet[294]: E0606 15:34:43.649438     294 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"kind-worker3\" not found" node="kind-worker3"
Jun 06 15:34:43 kind-worker3 kubelet[294]: E0606 15:34:43.679661     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:43 kind-worker3 kubelet[294]: I0606 15:34:43.723904     294 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker3"
Jun 06 15:34:43 kind-worker3 kubelet[294]: E0606 15:34:43.780440     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:43 kind-worker3 kubelet[294]: E0606 15:34:43.881117     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:43 kind-worker3 kubelet[294]: E0606 15:34:43.981976     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:43 kind-worker3 kubelet[294]: I0606 15:34:43.989230     294 kubelet_node_status.go:73] "Successfully registered node" node="kind-worker3"
Jun 06 15:34:44 kind-worker3 kubelet[294]: E0606 15:34:44.082629     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:44 kind-worker3 kubelet[294]: E0606 15:34:44.183495     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:44 kind-worker3 kubelet[294]: E0606 15:34:44.284143     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:44 kind-worker3 kubelet[294]: E0606 15:34:44.384610     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:44 kind-worker3 kubelet[294]: E0606 15:34:44.484858     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:44 kind-worker3 kubelet[294]: E0606 15:34:44.585337     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:44 kind-worker3 kubelet[294]: E0606 15:34:44.685681     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:44 kind-worker3 kubelet[294]: E0606 15:34:44.786104     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:44 kind-worker3 kubelet[294]: E0606 15:34:44.886610     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:44 kind-worker3 kubelet[294]: E0606 15:34:44.987440     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:45 kind-worker3 kubelet[294]: E0606 15:34:45.087845     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:45 kind-worker3 kubelet[294]: E0606 15:34:45.188718     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:45 kind-worker3 kubelet[294]: E0606 15:34:45.289696     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:45 kind-worker3 kubelet[294]: E0606 15:34:45.390096     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:45 kind-worker3 kubelet[294]: E0606 15:34:45.490516     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:45 kind-worker3 kubelet[294]: E0606 15:34:45.590946     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:45 kind-worker3 kubelet[294]: E0606 15:34:45.691323     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:45 kind-worker3 kubelet[294]: E0606 15:34:45.791965     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
Jun 06 15:34:45 kind-worker3 kubelet[294]: E0606 15:34:45.893735     294 kubelet.go:2419] "Error getting node" err="node \"kind-worker3\" not found"
